# Generated by Django 4.1.5 on 2023-02-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quizcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='level',
            new_name='type',
        ),
    ]
