# Generated by Django 4.1.5 on 2023-02-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_branches_title_alter_quizcategory_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name_plural': 'Branch'},
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='branch',
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branches'),
        ),
    ]
