# Generated by Django 4.1.5 on 2023-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_type_alter_quizquestions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
