# Generated by Django 4.1.5 on 2023-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_quizquestions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='title',
            field=models.CharField(default='Select Something', max_length=100),
        ),
    ]
