# Generated by Django 4.1.5 on 2023-02-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_branches_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='branch',
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizcategory'),
        ),
    ]
