# Generated by Django 4.1.5 on 2023-02-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_quizquestions_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branches'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
