# Generated by Django 4.1.5 on 2023-02-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quizquestions_branch_alter_quizquestions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmittedanswer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branches'),
        ),
        migrations.AddField(
            model_name='usersubmittedanswer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizcategory'),
        ),
    ]
