# Generated by Django 4.1.5 on 2023-02-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_usersubmittedanswer_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
